### ISSUE TITLE
Spiel Absturz zwingt einen zum Reboot des Rechners

### ISSUE THREAD

**Issue by ghost** [R0binSmit/RPG2D#12]
Wenn das Spiel abstürzt, dann kann man weder raustabben, noch den Task-Manager öffnen und bei einem neuen virtuellen Desktop ist das Spiel auch vorhanden. Hier ist zu beachten, dass das Spiel im Vollbildmodus hart gesetzt worden ist und man deshalb nichts mehr machen konnte. Es soll nun nach einem Mechanismus gefunden werden, der bei zukünftigen Abstürzen das Spiel automatisch schließt.

**Comment by R0binSmit** [comment]
Dies ist ein direkter Bug. Ich habe ein Breakpoint in der Entwicklungsumgebung gesetzt und das Spiel war im FullScreen über die Entwicklungsumgebung, währen der Breakpoint erreicht wurde. Dadurch konnte ich in Game nichts mehr tun und die Entwicklungsumgebung auch nicht mehr in den Vordergrund holen.
